### PR TITLE
feat: SCSS

### PR DESCRIPTION
**Pull request by vltansky**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

relevant to: 
https://github.com/h5bp/html5-boilerplate/issues/2274 
https://github.com/h5bp/html5-boilerplate/pull/2282

### CODE REVIEW

**Comment by roblarsen** [comment]
As your PR shows, there is no real benefit to using SCSS here in this project. I abandoned that idea when I initially created this project ([You can see how I removed "scss" from the issue titled in issue #3](https://github.com/h5bp/main.css/issues/3) because it doesn't do anything useful. They're just CSS files renamed. IF it actually made a difference I would do it, but it doesn't so I would prefer to keep this as vanilla CSS.

**Comment by vltansky** [comment]
I do agree that there is no benefit of using SCSS in the project itself. But I think there is a benefit of using SCSS for the usage and customization of the library.
For example:

1. Users can import only needed parts directly into their SCSS, lets say I'm using it in my angular project:
`styles.scss`:
```scss
@import "~main.css/src/base";
@import "~main.css/src/helpers";
```

2. Lets say in `_base.scss` we change 
```css
.html{
...
color: #222
}```
to
```scss
$html_color: #222!default;
$selection_color: #b3d4fc!default;
.html{
...
color: $html-color
}


::-moz-selection {
  background: $selection_color:
  text-shadow: none;
}

::selection {
  background: $selection_color:;
  text-shadow: none;
}
```

then in `style.scss` I can import and override color:
```scss
$html-color: #000;
$selection_color: blue;
@import "~main.css/src/base";
```
or even use CSS vars:

```scss
$html-color: #{var(--body)};
$selection_color: #{var(--primary)};
@import "~main.css/src/base";
```
3. Also, this means that when I'll run `npm update main.css` my imports will get latest

**Comment by roblarsen** [comment]
You can already import just the parts you need ([we have always shipped the component parts in addition to the bundled main.css](https://github.com/h5bp/main.css/tree/master/dist)) and if an end user wants to convert to sass they just change the file names. I went through this whole line of reasoning and abandoned it as not worth the overhead and not generic enough for all users.

**Comment by vltansky** [comment]
Why its not generic when you have CSS files in `dist` folder and scss file in `src` folder. User can use whatever is good for him.
Same way as bootstrap shipped. https://getbootstrap.com/docs/4.5/getting-started/theming/

**Comment by roblarsen** [comment]
Using web standard technology throughout the process is by nature more generic than using a pre-processor. Not everyone knows about SASS/SCSS etc. so there's one less hurdle for people when working with this project. 

If this were Bootstrap or even if there was any actual benefit to authoring in sass I would do so. As I mentioned previously  **I initially intended to implement what you're proposing and rejected it after having done the work**. 

See #3 

>Okay! Months later I return from the wilderness.

> This issue was originally about pre-processors and all that and after kicking the tires on it, it seems like a waste of time, so this is now simpler.

>Break main.css into muliple files
combine them back together to create voltron the new main.css
copy the component files to ./dist/ so that people can ingest individual files as needed
This will be the 1.0.0 release 🥇

I literally built the project using sass and decided it wasn't worth it.

**Pull request closed without merging**
